name: CI with Gradle

# develop, main 브랜치에 PR이 생성될 때 CI 파이프라인 실행
on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    # 필요한 secret 값들 추가
    env:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      OPENAI_TIMEOUT: ${{ secrets.OPENAI_TIMEOUT }}

    steps:
      # GitHub 저장소 코드 체크아웃
      - uses: actions/checkout@v4

      # JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 테스트 실행
      - name: Run Tests
        run: ./gradlew clean test --info --stacktrace

      # 테스트 실패 시 HTML 리포트 업로드
      - name: Upload Test Report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test
